apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: scrumdinger-system

spec:
  type: ClusterIP

  ports:
  - name: auth
    port: 6001
    targetPort: auth
  - name: auth-debug
    port: 6010
    targetPort: auth-debug
