apiVersion: v1
kind: Service
metadata:
  name: scrumdinger-service
  namespace: scrumdinger-system

spec:
  type: ClusterIP

  ports:
  - name: scrumdinger
    port: 3000
    targetPort: scrumdinger
  - name: scrumdinger-debug
    port: 3010
    targetPort: scrumdinger-debug
  - name: metrics
    port: 4000
    targetPort: metrics
  - name: metrics-debug
    port: 4010
    targetPort: metrics-debug
  - name: prometheus
    port: 4020
    targetPort: metrics-prom
