apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/scrumdinger/
  - ./dev-scrumdinger-configmap.yaml
patches:
  - path: ./dev-scrumdinger-patch-deploy.yaml
  - path: ./dev-scrumdinger-patch-service.yaml
images:
  - name: scrumdinger-image
    newName: localhost/angrieralien/scrumdinger
    newTag: 0.0.1
  - name: metrics-image
    newName: localhost/angrieralien/metrics
    newTag: 0.0.1
